channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.1.1
- pip:
  - mlflow==2.19.0
  - asyncio==3.4.3
  - cloudpickle==3.1.2
  - numpy==1.26.0
  - pandas==2.2.3
  - psutil==5.9.6
  - scikit-learn==1.6.0
  - scipy==1.14.1
name: mlflow-env
